### ISSUE TITLE
No more working after upgrading to Docker 1.10

### ISSUE THREAD

**Issue by zedtux** [sameersbn/docker-skype#17]
While Skype is working fine with Docker 1.9, after upgrading to Docker engine 1.10, Skype is not showing up.

This is surly due to the new security features.

**Comment by garex** [comment]
Strange... It's still works for me. But I just reinstalled fresh latest ubuntu above linux mint.

Anyway I think it's an issue on your local install side.

**Comment by zedtux** [comment]
Well I was thinking the same so I did the following :
- `rm -rf /var/lib/docker/`
- `service docker restart`
- `apt-get install docker-engine=1.9.1-0~stretch` <= Downgrade Docker to 1.9
- `skype` (Wrapper script which downloaded again the docker-skype image and do on)
- Skype worked
- `apt-get install docker-engine`  <= Update Docker to 1.10
- `skype` the wrapper run without any errors but skype is not showing up

Anything I could try else ? I don't care to destroy my containers and re-build them again.

**Comment by garex** [comment]
Try to first stop docker.

Then purge it, then remove all in those var/lib and etc

Then reinstall to 1.10

---

Alexander Ustimenko
    +7 (952) 918-02-20

2016-02-25 19:16 GMT+06:00 Guillaume Hain notifications@github.com:

**Comment by sameersbn** [comment]
I am able to use skype with latest docker on ubuntu 14.04.
generally you only want to remove sameersbn/skype image and repull. since you already went and deleted `/var/lib/docker`, try:
1. uninstall docker-engine
2. reboot host
3. rm -rf /var/lib/docker
4. install docker-engine 1.10.2
5. download and install the skype wrapper

**Comment by garex** [comment]
Aaah! May be you just need manually remove skype and skype wrapper scripts?

**Comment by zedtux** [comment]
Okay, thank you guys, I'll give it a try !

**Comment by dradux** [comment]
I am having a similar issue. I did not have docker-skype working before as my initial usage was with a docker 1.10 engine. After downloading a new instance of docker-skype, installing wrapper scripts and starting with `skype-wrapper skype`  I get the following:

<pre><code>
Cleaning up stopped skype instances...
Starting skype...
</code></pre>

And skype is not started.

I tried @sameersbn suggestion and get the same results (no skype).

I then tried @zedtux suggestion to downgrade docker-engine to 1.9 and skype works fine.

Also note that I am running a pure debian instance (not ubuntu) with openbox (no gnome/gdm).

**Comment by garex** [comment]
Still cant' repeat.

Ok, let's debug:
- Show us `docker ps -a | grep skype`
- `nano /usr/local/bin/skype-wrapper`
- Add echo before this line and tell us what will be there https://github.com/sameersbn/docker-skype/blob/master/scripts/skype-wrapper#L99

**Comment by dradux** [comment]
<code><pre>
docker -v
Docker version 1.10.2, build c3959b1
</code></pre>
<code><pre>
drad@thez:~$ docker ps -a | grep skype
95ac122878ba        sameersbn/skype:latest   "/sbin/entrypoint.sh "   2 minutes ago       Exited (1) 2 minutes ago                       desperate_panini
</code></pre>

I get the following when I echo L99:

<pre><code>
Cleaning up stopped skype instances...
Starting skype...
</code></pre>

Which is probably not real useful. I added an echo of SUDO which shows no sudo used. I also took the `> /dev/null` off L99 and I then get the following:

<pre><code>
Cleaning up stopped skype instances...
Starting skype...
SUDO=
docker run -d --env=USER_UID=1000 --env=USER_GID=1000 --env=DISPLAY --env=XAUTHORITY=/tmp/.docker.xauth --env=TZ=EST --device /dev/video0:/dev/video0 --volume=/home/drad/.Skype:/home/skype/.Skype --volume=/home/drad/Downloads:/home/skype/Downloads --volume=/tmp/.X11-unix:/tmp/.X11-unix --volume=/tmp/.docker.xauth:/tmp/.docker.xauth --volume=/run/user/1000/pulse:/run/pulse sameersbn/skype:latest skype
</code></pre>

I then downgraded with:

<pre><code>
$ apt-get install docker-engine=1.9.1-0~stretch
$ service docker restart
$ docker -v
Docker version 1.9.1, build a34a1d5
</code></pre>

And skype starts without an issue.

Let me know if you need anything else.

**Comment by garex** [comment]
What about `docker logs desperate_panini`? Or something else.

It should tell us what's wrong and you will not see it as it starts in detached state.

**Comment by dradux** [comment]
<pre><code>
drad@thez:~$ skype-wrapper skype
Cleaning up stopped skype instances...
Starting skype...
drad@thez:~$ docker ps -a
CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS                     PORTS               NAMES
4569b708848f        sameersbn/skype:latest   "/sbin/entrypoint.sh "   9 seconds ago       Exited (1) 3 seconds ago                       loving_bartik
drad@thez:~$ docker logs loving_bartik
drad@thez:~$
</code></pre>

I then stopped docker and started it with debug enabled and get the followiing:

<pre><code>
DEBU[0029] Calling GET /v1.22/containers/json
DEBU[0029] GET /v1.22/containers/json?all=1
DEBU[0029] Calling GET /v1.22/containers/5a0c8aa08f2d/json
DEBU[0029] GET /v1.22/containers/5a0c8aa08f2d/json
DEBU[0029] Calling GET /v1.22/containers/5a0c8aa08f2d/json
DEBU[0029] GET /v1.22/containers/5a0c8aa08f2d/json
DEBU[0029] Calling DELETE /v1.22/containers/5a0c8aa08f2d
DEBU[0029] DELETE /v1.22/containers/5a0c8aa08f2d
DEBU[0029] devmapper: DeleteDevice(hash=08a46b3ad058b213130a68d7d575bce28ecb51050cd525551be64220c6901085 syncDelete=false) START
DEBU[0029] devmapper: issueDiscard(device: 08a46b3ad058b213130a68d7d575bce28ecb51050cd525551be64220c6901085). START
DEBU[0029] devmapper: activateDeviceIfNeeded(08a46b3ad058b213130a68d7d575bce28ecb51050cd525551be64220c6901085)
DEBU[0029] devmapper: issueDiscard(device: 08a46b3ad058b213130a68d7d575bce28ecb51050cd525551be64220c6901085). END
DEBU[0029] devmapper: deactivateDevice(08a46b3ad058b213130a68d7d575bce28ecb51050cd525551be64220c6901085)
DEBU[0029] devmapper: removeDevice START(docker-252:2-11010049-08a46b3ad058b213130a68d7d575bce28ecb51050cd525551be64220c6901085)
DEBU[0030] devmapper: removeDevice END(docker-252:2-11010049-08a46b3ad058b213130a68d7d575bce28ecb51050cd525551be64220c6901085)
DEBU[0030] devmapper: deactivateDevice END(08a46b3ad058b213130a68d7d575bce28ecb51050cd525551be64220c6901085)
DEBU[0030] devmapper: unregisterDevice(43, 08a46b3ad058b213130a68d7d575bce28ecb51050cd525551be64220c6901085)
DEBU[0030] devmapper: DeleteDevice(hash=08a46b3ad058b213130a68d7d575bce28ecb51050cd525551be64220c6901085 syncDelete=false) END
DEBU[0030] devmapper: DeleteDevice(hash=08a46b3ad058b213130a68d7d575bce28ecb51050cd525551be64220c6901085-init syncDelete=false) START
DEBU[0030] devmapper: issueDiscard(device: 08a46b3ad058b213130a68d7d575bce28ecb51050cd525551be64220c6901085-init). START
DEBU[0030] devmapper: activateDeviceIfNeeded(08a46b3ad058b213130a68d7d575bce28ecb51050cd525551be64220c6901085-init)
DEBU[0030] devmapper: issueDiscard(device: 08a46b3ad058b213130a68d7d575bce28ecb51050cd525551be64220c6901085-init). END
DEBU[0030] devmapper: deactivateDevice(08a46b3ad058b213130a68d7d575bce28ecb51050cd525551be64220c6901085-init)
DEBU[0030] devmapper: removeDevice START(docker-252:2-11010049-08a46b3ad058b213130a68d7d575bce28ecb51050cd525551be64220c6901085-init)
DEBU[0030] devmapper: removeDevice END(docker-252:2-11010049-08a46b3ad058b213130a68d7d575bce28ecb51050cd525551be64220c6901085-init)
DEBU[0030] devmapper: deactivateDevice END(08a46b3ad058b213130a68d7d575bce28ecb51050cd525551be64220c6901085-init)
DEBU[0030] devmapper: unregisterDevice(42, 08a46b3ad058b213130a68d7d575bce28ecb51050cd525551be64220c6901085-init)
DEBU[0030] devmapper: DeleteDevice(hash=08a46b3ad058b213130a68d7d575bce28ecb51050cd525551be64220c6901085-init syncDelete=false) END
DEBU[0030] Calling POST /v1.22/containers/create
DEBU[0030] POST /v1.22/containers/create
DEBU[0030] form data: {"AttachStderr":false,"AttachStdin":false,"AttachStdout":false,"Cmd":["skype"],"Domainname":"","Entrypoint":null,"Env":["USER_UID=1000","USER_GID=1000","DISPLAY=:0.0","XAUTHORITY=/tmp/.docker.xauth","TZ=EST"],"HostConfig":{"Binds":["/home/drad/.Skype:/home/skype/.Skype","/home/drad/downloads:/home/skype/Downloads","/tmp/.X11-unix:/tmp/.X11-unix","/tmp/.docker.xauth:/tmp/.docker.xauth","/run/user/1000/pulse:/run/pulse"],"BlkioDeviceReadBps":null,"BlkioDeviceReadIOps":null,"BlkioDeviceWriteBps":null,"BlkioDeviceWriteIOps":null,"BlkioWeight":0,"BlkioWeightDevice":null,"CapAdd":null,"CapDrop":null,"CgroupParent":"","ConsoleSize":[0,0],"ContainerIDFile":"","CpuPeriod":0,"CpuQuota":0,"CpuShares":0,"CpusetCpus":"","CpusetMems":"","Devices":[{"CgroupPermissions":"rwm","PathInContainer":"/dev/video0","PathOnHost":"/dev/video0"}],"Dns":[],"DnsOptions":[],"DnsSearch":[],"ExtraHosts":null,"GroupAdd":null,"IpcMode":"","Isolation":"","KernelMemory":0,"Links":null,"LogConfig":{"Config":{},"Type":""},"Memory":0,"MemoryReservation":0,"MemorySwap":0,"MemorySwappiness":-1,"NetworkMode":"default","OomKillDisable":false,"OomScoreAdj":0,"PidMode":"","PidsLimit":0,"PortBindings":{},"Privileged":false,"PublishAllPorts":false,"ReadonlyRootfs":false,"RestartPolicy":{"MaximumRetryCount":0,"Name":"no"},"SecurityOpt":null,"ShmSize":0,"UTSMode":"","Ulimits":null,"VolumeDriver":"","VolumesFrom":null},"Hostname":"","Image":"sameersbn/skype:latest","Labels":{},"NetworkingConfig":{"EndpointsConfig":{}},"OnBuild":null,"OpenStdin":false,"StdinOnce":false,"StopSignal":"SIGTERM","Tty":false,"User":"","Volumes":{},"WorkingDir":""}
DEBU[0030] devmapper: AddDevice(hash=4fec822770d056855839133b7f4a86cb36a7ec68df7dba2bf637d07a014d113c-init basehash=1aa397a163cfc136d78d68bc0be7af3ab7740845926d2548226bf077d61428b4)
DEBU[0031] devmapper: registerDevice(44, 4fec822770d056855839133b7f4a86cb36a7ec68df7dba2bf637d07a014d113c-init)
DEBU[0031] devmapper: AddDevice(hash=4fec822770d056855839133b7f4a86cb36a7ec68df7dba2bf637d07a014d113c-init basehash=1aa397a163cfc136d78d68bc0be7af3ab7740845926d2548226bf077d61428b4) END
DEBU[0031] devmapper: activateDeviceIfNeeded(4fec822770d056855839133b7f4a86cb36a7ec68df7dba2bf637d07a014d113c-init)
DEBU[0031] devmapper: UnmountDevice(hash=4fec822770d056855839133b7f4a86cb36a7ec68df7dba2bf637d07a014d113c-init)
DEBU[0031] devmapper: Unmount(/var/lib/docker/devicemapper/mnt/4fec822770d056855839133b7f4a86cb36a7ec68df7dba2bf637d07a014d113c-init)
DEBU[0031] devmapper: Unmount done
DEBU[0031] devmapper: deactivateDevice(4fec822770d056855839133b7f4a86cb36a7ec68df7dba2bf637d07a014d113c-init)
DEBU[0031] devmapper: removeDevice START(docker-252:2-11010049-4fec822770d056855839133b7f4a86cb36a7ec68df7dba2bf637d07a014d113c-init)
DEBU[0031] devmapper: removeDevice END(docker-252:2-11010049-4fec822770d056855839133b7f4a86cb36a7ec68df7dba2bf637d07a014d113c-init)
DEBU[0031] devmapper: deactivateDevice END(4fec822770d056855839133b7f4a86cb36a7ec68df7dba2bf637d07a014d113c-init)
DEBU[0031] devmapper: UnmountDevice(hash=4fec822770d056855839133b7f4a86cb36a7ec68df7dba2bf637d07a014d113c-init) END
DEBU[0031] devmapper: AddDevice(hash=4fec822770d056855839133b7f4a86cb36a7ec68df7dba2bf637d07a014d113c basehash=4fec822770d056855839133b7f4a86cb36a7ec68df7dba2bf637d07a014d113c-init)
DEBU[0031] devmapper: registerDevice(45, 4fec822770d056855839133b7f4a86cb36a7ec68df7dba2bf637d07a014d113c)
DEBU[0031] devmapper: AddDevice(hash=4fec822770d056855839133b7f4a86cb36a7ec68df7dba2bf637d07a014d113c basehash=4fec822770d056855839133b7f4a86cb36a7ec68df7dba2bf637d07a014d113c-init) END
DEBU[0031] devmapper: activateDeviceIfNeeded(4fec822770d056855839133b7f4a86cb36a7ec68df7dba2bf637d07a014d113c)
DEBU[0031] container mounted via layerStore: /var/lib/docker/devicemapper/mnt/4fec822770d056855839133b7f4a86cb36a7ec68df7dba2bf637d07a014d113c/rootfs
DEBU[0031] devmapper: UnmountDevice(hash=4fec822770d056855839133b7f4a86cb36a7ec68df7dba2bf637d07a014d113c)
DEBU[0031] devmapper: Unmount(/var/lib/docker/devicemapper/mnt/4fec822770d056855839133b7f4a86cb36a7ec68df7dba2bf637d07a014d113c)
DEBU[0032] devmapper: Unmount done
DEBU[0032] devmapper: deactivateDevice(4fec822770d056855839133b7f4a86cb36a7ec68df7dba2bf637d07a014d113c)
DEBU[0032] devmapper: removeDevice START(docker-252:2-11010049-4fec822770d056855839133b7f4a86cb36a7ec68df7dba2bf637d07a014d113c)
DEBU[0032] devmapper: removeDevice END(docker-252:2-11010049-4fec822770d056855839133b7f4a86cb36a7ec68df7dba2bf637d07a014d113c)
DEBU[0032] devmapper: deactivateDevice END(4fec822770d056855839133b7f4a86cb36a7ec68df7dba2bf637d07a014d113c)
DEBU[0032] devmapper: UnmountDevice(hash=4fec822770d056855839133b7f4a86cb36a7ec68df7dba2bf637d07a014d113c) END
DEBU[0032] Calling POST /v1.22/containers/29b0d6fc879b824f9c0948873556975e6c1a2cd9cfec0423f0c80f829d0ab149/start
DEBU[0032] POST /v1.22/containers/29b0d6fc879b824f9c0948873556975e6c1a2cd9cfec0423f0c80f829d0ab149/start
DEBU[0032] devmapper: activateDeviceIfNeeded(4fec822770d056855839133b7f4a86cb36a7ec68df7dba2bf637d07a014d113c)
DEBU[0032] container mounted via layerStore: /var/lib/docker/devicemapper/mnt/4fec822770d056855839133b7f4a86cb36a7ec68df7dba2bf637d07a014d113c/rootfs
DEBU[0032] Assigning addresses for endpoint serene_tesla's interface on network bridge
DEBU[0032] RequestAddress(LocalDefault/172.17.0.0/16, <nil>, map[])
DEBU[0032] Assigning addresses for endpoint serene_tesla's interface on network bridge
WARN[0033] Your kernel does not support OOM notifications: There is no path for "memory" in state
WARN[0033] Your kernel does not support OOM notifications: There is no path for "memory" in state
DEBU[0036] Releasing addresses for endpoint serene_tesla's interface on network bridge
DEBU[0036] ReleaseAddress(LocalDefault/172.17.0.0/16, 172.17.0.2)
DEBU[0036] devmapper: UnmountDevice(hash=4fec822770d056855839133b7f4a86cb36a7ec68df7dba2bf637d07a014d113c)
DEBU[0036] devmapper: Unmount(/var/lib/docker/devicemapper/mnt/4fec822770d056855839133b7f4a86cb36a7ec68df7dba2bf637d07a014d113c)
DEBU[0036] devmapper: Unmount done
DEBU[0036] devmapper: deactivateDevice(4fec822770d056855839133b7f4a86cb36a7ec68df7dba2bf637d07a014d113c)
DEBU[0036] devmapper: removeDevice START(docker-252:2-11010049-4fec822770d056855839133b7f4a86cb36a7ec68df7dba2bf637d07a014d113c)
DEBU[0036] devmapper: removeDevice END(docker-252:2-11010049-4fec822770d056855839133b7f4a86cb36a7ec68df7dba2bf637d07a014d113c)
DEBU[0036] devmapper: deactivateDevice END(4fec822770d056855839133b7f4a86cb36a7ec68df7dba2bf637d07a014d113c)
DEBU[0036] devmapper: UnmountDevice(hash=4fec822770d056855839133b7f4a86cb36a7ec68df7dba2bf637d07a014d113c) END
</code></pre>

Nothing stands out to me as an issue but perhaps you can see something. Anything else I can do to see why it exited (1)?

**Comment by garex** [comment]
I see "WARN Your kernel does not support blablabla".

May be here an issue?

Try to downgrade to 1.9 and compare debug logs then.

---

Alexander Ustimenko
    +7 (952) 918-02-20

2016-03-01 17:12 GMT+06:00 David Rader notifications@github.com:

**Comment by dradux** [comment]
I saw that too but since my kernel did not change I disgregarded. I ran debug for docker 1.9.1 and docker 1.10.2, there are quite a few differences in what and how things are being called. Both give a WARN on "Your kernel does not support OOM notifications; however, 1.10.2 releases addresses and unmounts the device whereas 1.9.1 does not.
[issue17_docker-1.9.1.txt](https://github.com/sameersbn/docker-skype/files/152885/issue17_docker-1.9.1.txt)
[issue17_docker-1.10.2.txt](https://github.com/sameersbn/docker-skype/files/152888/issue17_docker-1.10.2.txt)

I am running debian sid with a 4.3.5-1 kernel: `Linux thez 4.3.0-1-amd64 #1 SMP Debian 4.3.5-1 (2016-02-06) x86_64 GNU/Linux`

**Comment by garex** [comment]
I also dont' see anything.

Try to remove all skype-related images, remove all skype-related
containers, pull latest image and run again. See what important changed.

https://github.com/docker/docker/blob/master/CHANGELOG.md#1100-2016-02-04

---

Alexander Ustimenko
    +7 (952) 918-02-20

2016-03-01 20:02 GMT+06:00 David Rader notifications@github.com:

**Comment by spijet** [comment]
It seems that Docker 1.10 enables User Namespaces  by default on some distros (I may be wrong here).
I use Docker 1.10 on Gentoo (amd64 and someparts are ~amd64). When I start the daemon with `--userns-remap=default` I get the same error. If I start it without the option -- it works as intended (except that I don't get any sound -- Skype appears to use some "Virtual Device" and I don't see Skype in host's `pavucontrol`).

**Comment by dradux** [comment]
thanks @spijet , I tried daemon with --userns-remap=default and get `docker: Error response from daemon: Container command could not be invoked..` If I start the daemon with no --userns-remap=default (e.g. `docker daemon --`) I get the same response as above (skype is not started).

**Comment by mfournier** [comment]
Just ran into this issue too, after upgrading to 1.10. I was able to make skype work by changing the call to docker at the bottom of the skype-wrapper script to read `docker run --privileged [...]`.

So more of a workaround than a real solution, but at least confirms something permissions-related changed between docker 1.9 and 1.10. No selinux/apparmor involved in my case, BTW.

**Comment by damien-carcel** [comment]
I ran in the same problem, I confirm that @mfournier solution works for me too.

@sameersbn: Nice container btw, thank you for it.

**Comment by spijet** [comment]
Suddenly, this container stopped working for me too. Skype binary throws error code 1 and exits. There's only one line in docker logs:
`chown: cannot access '/home/skype/Downloads/.gvfs': Permission denied`
Recently I've rebuilt gvfs on my system (Gentoo), but it shouldn't be related to this, as this is a container.

**Comment by spijet** [comment]
Turned out that there _were_ some GVFS problems there. I tried to create a new dir, `~/skypefiles` and set it as $DOWNLOAD_DIR in the wrapper -- and it worked.

~~ADD@15 minutes later: now it starts and stays in 'connecting' state (spinning skype icon) forever. :D~~
Figured it out. Docker daemon had started before wicd and did not set up a bridge address. :)

**Comment by dradux** [comment]
I implemented the solution from @spijet and upgraded to current version of docker-engine, my instance of skype started! I then removed the solution from @spijet (back to a clean clone) and skype started. Apparently something in the latest docker-skype addressed the issue.

**Comment by simao** [comment]
I am getting a similar problem with docker 1.10.3 under arch linux. Running skype returns nothing and no containers are started:

```
~   skype
which: no skype in (/usr/sbin:/usr/bin:/sbin:/bin)
Cleaning up stopped skype instances...
Starting skype...
4e8723b1ab0b40241ae529b7f8363756bda7ba7c339d7d54d2c47d59e17e3360
 ~   docker logs 4e8723b1ab0b40241ae529b7f8363756bda7ba7c339d7d54d2c47d59e17e3360
No protocol specified
 ~   
```

Any ideas?

**Comment by sameersbn** [comment]
I just setup a debian:jessie VM to test this issue and I am not seeing any issue with the latest skype version.

``` bash
$ docker ps 
CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS              PORTS               NAMES
0d070cd54415        sameersbn/skype:latest   "/sbin/entrypoint.sh "   18 seconds ago      Up 17 seconds                           high_hypatia
```

**Comment by dradux** [comment]
@simao , can you please specify what version of docker-engine you are using and what from this thread you have tried? Also, are you on the latest of docker-skype?

**Comment by simao** [comment]
I just tried again, with `--privileged` and it works again, so I am not sure what I was doing wrong before.

Here is the output for `docker version`.

Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Sat Mar 12 19:18:57 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Sat Mar 12 19:18:57 2016
 OS/Arch:      linux/amd64
 ~

**Comment by dradux** [comment]
You do understand that --privileged  has security implications I hope. This lets the skype container have more access to your host. Some people use docker-skype to keep skype contained in its own sandbox due to the source being propriatary (and now one knows what it is reporting back to the skype servers). Running with --privileged sacrafices some of this sandboxing.

My docker info is nearly identical and I have docker-skype working without the --privliged flag:

Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:43:40 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:43:40 2016
 OS/Arch:      linux/amd64

I am running docker-skype from a clone from https://github.com/sameersbn/docker-skype.git with no changes to it or to docker (daemon).

**Comment by sameersbn** [comment]
Do you have selinux installed/enabled by any chance?

**Comment by simao** [comment]
Yes I understand it has implications. I just wanted to try. 

I don't have selinux installed.

**Comment by zedtux** [comment]
I'm no more using Skype so I close the issue.
