### ISSUE TITLE
which: no skype in (/usr/sbin:/usr/bin:/sbin:/bin)

### ISSUE THREAD

**Issue by mikken** [sameersbn/docker-skype#5]
Skype is not launched here.
Also, issue with usermod (adding skype user to group 91, which does not exists in container machine).
This is a laptop with Arch and plain docker installed.

% docker version
Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.5.1
 Git commit:   f4bf5c7-dirty
 Built:        Wed Oct 14 11:17:02 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.5.1
 Git commit:   f4bf5c7-dirty
 Built:        Wed Oct 14 11:17:02 UTC 2015
 OS/Arch:      linux/amd64

% docker info
Containers: 1
Images: 12
Storage Driver: btrfs
 Build Version: Btrfs v4.2.1
 Library Version: 101
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.2.3-1-ARCH
Operating System: Arch Linux (containerized)
CPUs: 4
Total Memory: 7.696 GiB
Name: suns
ID: AZ47:NNAJ:YSV3:QE2R:CNHP:BSIQ:WNA4:BWXB:YL3X:3BTJ:WJBG:RPC2

(I have removed -d and /dev/null redirect from "docker run" command)

% skype
which: no skype in (/usr/sbin:/usr/bin:/sbin:/bin)
Cleaning up stopped skype instances...
cat: /etc/timezone: No such file or directory
Starting skype...
usermod: group '91' does not exist

**Comment by sameersbn** [comment]
it appears no group with GID 91 exists in the container, so the usermod fails. To fix this we will need to create a new group and assign it the GID 91 before doing usermod. Will make this changes soon,

**Comment by mikken** [comment]
Fix did not work very well:
% skype
which: no skype in (/usr/sbin:/usr/bin:/sbin:/bin)
Cleaning up stopped skype instances...
cat: /etc/timezone: No such file or directory
Starting skype...
groupadd: group 'video' already exists

And skype is still not started (container exits). Do you think it's due to wrong /dev/video0 permissions? Because skype not launching was my main problem.

**Comment by sameersbn** [comment]
hmm.. its because a group with the name `video` already exists. will change the name

**Comment by sameersbn** [comment]
please try after a while once the build is ready. let me know

**Comment by mikken** [comment]
Ok, works properly now.
