### ISSUE TITLE
Thank you good man!

### ISSUE THREAD

**Issue by garex** [sameersbn/docker-skype#6]
This issue is for +1 for those who finally solve skype-32bit-under-ubuntu-64bit issue as m$ft are lazy and can't provide adequate support for all platforms.

You are just saved our asses from stupid "sudo dpkg --add-architecture i386".

```
 _____ _                 _     __   __            __  __             
|_   _| |__   __ _ _ __ | | __ \ \ / /__  _   _  |  \/  | __ _ _ __  
  | | | '_ \ / _` | '_ \| |/ /  \ V / _ \| | | | | |\/| |/ _` | '_ \ 
  | | | | | | (_| | | | |   <    | | (_) | |_| | | |  | | (_| | | | |
  |_| |_| |_|\__,_|_| |_|_|\_\   |_|\___/ \__,_| |_|  |_|\__,_|_| |_|
```

**Comment by sameersbn** [comment]
Glad you like it :+1: 

> You are just saved our asses from stupid "sudo dpkg --add-architecture i386".

Had never thought about this.
